In [28]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

import tensorflow as tf

In [29]:
df = pd.read_csv("BostonHousing.csv")

In [30]:
df

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88,11.9

In [31]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [32]:
x

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,9.67
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273,21.0,396.90,7.88

In [33]:
y

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ...
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: medv, Length: 506, dtype: float64

In [34]:
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [17]:
df.tail()

        RM  LSTAT  PTRATIO      MEDV
484  6.593   9.67     21.0  470400.0
485  6.120   9.08     21.0  432600.0
486  6.976   5.64     21.0  501900.0
487  6.794   6.48     21.0  462000.0
488  6.030   7.88     21.0  249900.0

In [35]:
df.shape

(506, 14)

In [36]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=40)

In [37]:
x_train

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat
213,0.14052,0.0,10.59,0,0.489,6.375,32.3,3.9454,4,277,18.6,385.81,9.38
388,14.33370,0.0,18.10,0,0.700,4.880,100.0,1.5895,24,666,20.2,372.92,30.62
284,0.00906,90.0,2.97,0,0.400,7.088,20.8,7.3073,1,285,15.3,394.72,7.85
334,0.03738,0.0,5.19,0,0.515,6.310,38.5,6.4584,5,224,20.2,389.40,6.75
175,0.06664,0.0,4.05,0,0.510,6.546,33.1,3.1323,5,296,16.6,390.96,5.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
440,22.05110,0.0,18.10,0,0.740,5.818,92.4,1.8662,24,666,20.2,391.45,22.11
165,2.92400,0.0,19.58,0,0.605,6.101,93.0,2.2834,5,403,14.7,240.16,9.81
7,0.14455,12.5,7.87,0,0.524,6.172,96.1,5.9505,5,311,15.2,396.90,19.15
219,0.11425,0.0,13.89,1,0.550,6.373,92.4,3.3633,5,276,16.4,393.74,10.50
326,0.30347,0.0,7.38,0,0.493,6.312,28.9,5.4159,5,287,19.6,396.90,6.15

In [38]:
scalar = StandardScaler()
x_train = scalar.fit_transform(x_train)
x_test = scalar.transform(x_test)

In [40]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential()
model.add(Dense(64,activation='relu',input_shape=(13,)))
model.add(Dense(32,activation='relu',))
model.add(Dense(1))

C:\Users\hp\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [41]:
model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

In [42]:
model.fit(
    x_train,
    y_train,
    epochs=100,
    batch_size=16
)

Epoch 1/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 543.5069 - mae: 21.9122
Epoch 2/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 500.8350 - mae: 20.6199
Epoch 3/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 330.2560 - mae: 16.6151
Epoch 4/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 169.3825 - mae: 11.2674
Epoch 5/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 74.0449 - mae: 6.9073
Epoch 6/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 41.4726 - mae: 5.0233
Epoch 7/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 30.4322 - mae: 4.1604
Epoch 8/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 25.6348 - mae: 3.7348
Epoch 9/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 20.9017 - mae: 3.3408
Epoch 10/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 20.6358 - mae: 3.3368
Epoch 11/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 16.5443 - mae: 3.1473
Epoch 12/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 18.2919 - mae: 3.1185
Epoch 13/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 15.7671 - mae: 2.9476
Epoch 14/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 20.4005 - mae: 3.1644
Epoch 15/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 15.7791 - mae: 2.8170
Epoch 16/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 14.9538 - mae: 2.8288
Epoch 17/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 16.2403 - mae: 2.8047
Epoch 18/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 13.7347 - mae: 2.6233
Epoch 19/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 16.5994 - mae: 2.8850
Epoch 20/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11.0071 - mae: 2.5347
Epoch 21/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.9118 - mae: 2.6069
Epoch 22/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 16.8824 - mae: 2.6086
Epoch 23/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 13.2900 - mae: 2.5432
Epoch 24/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 13.4336 - mae: 2.5315
Epoch 25/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 13.7357 - mae: 2.4454
Epoch 26/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10.8208 - mae: 2.3469
Epoch 27/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10.7995 - mae: 2.3384
Epoch 28/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 16.2664 - mae: 2.6416
Epoch 29/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10.2561 - mae: 2.3045
Epoch 30/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 15.6961 - mae: 2.5282
Epoch 31/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10.3314 - mae: 2.3520
Epoch 32/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10.6551 - mae: 2.2361
Epoch 33/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.8778 - mae: 2.4427
Epoch 34/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.3900 - mae: 2.3553
Epoch 35/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9.4295 - mae: 2.1665
Epoch 36/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 13.5832 - mae: 2.5394
Epoch 37/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9.8901 - mae: 2.2217
Epoch 38/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9.7375 - mae: 2.2280
Epoch 39/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.8539 - mae: 2.1702
Epoch 40/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10.3810 - mae: 2.1618
Epoch 41/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10.8773 - mae: 2.3205
Epoch 42/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.4543 - mae: 2.1018
Epoch 43/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9.4993 - mae: 2.2000
Epoch 44/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.7795 - mae: 2.0750
Epoch 45/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9.3699 - mae: 2.2280
Epoch 46/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.5909 - mae: 2.0829
Epoch 47/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9.6751 - mae: 2.1691
Epoch 48/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.3285 - mae: 2.1151
Epoch 49/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10.2492 - mae: 2.2639
Epoch 50/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9.0767 - mae: 2.0685
Epoch 51/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.6004 - mae: 2.1419
Epoch 52/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11.1070 - mae: 2.1785
Epoch 53/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6019 - mae: 2.0233
Epoch 54/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 11.5093 - mae: 2.1984
Epoch 55/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9.7220 - mae: 2.1132
Epoch 56/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9.6427 - mae: 2.1431
Epoch 57/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.5575 - mae: 2.0783
Epoch 58/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.4274 - mae: 1.9414
Epoch 59/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9.9369 - mae: 2.1179
Epoch 60/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.4459 - mae: 1.9759
Epoch 61/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.5667 - mae: 2.1125
Epoch 62/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.8591 - mae: 1.9662
Epoch 63/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.6254 - mae: 1.9921
Epoch 64/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.6431 - mae: 2.1311
Epoch 65/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.3046 - mae: 1.9997
Epoch 66/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8057 - mae: 1.8902
Epoch 67/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10.8690 - mae: 2.1975
Epoch 68/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.1321 - mae: 2.0424
Epoch 69/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9.6069 - mae: 2.1192
Epoch 70/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.1737 - mae: 1.9395
Epoch 71/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.1728 - mae: 1.9659
Epoch 72/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.8819 - mae: 2.0443
Epoch 73/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.7956 - mae: 2.1116
Epoch 74/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.0850 - mae: 2.0137
Epoch 75/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.6496 - mae: 2.0213
Epoch 76/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.4159 - mae: 2.0051
Epoch 77/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.7502 - mae: 1.9033
Epoch 78/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9.2407 - mae: 2.1939
Epoch 79/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.6381 - mae: 1.9784
Epoch 80/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.8494 - mae: 2.0052
Epoch 81/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.1555 - mae: 1.9005
Epoch 82/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 10.3401 - mae: 2.1347
Epoch 83/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9256 - mae: 1.9268
Epoch 84/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 9.0671 - mae: 2.1066
Epoch 85/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.0205 - mae: 1.9790
Epoch 86/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5.4937 - mae: 1.7270
Epoch 87/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3571 - mae: 1.8728
Epoch 88/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.2007 - mae: 1.7729
Epoch 89/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.6110 - mae: 1.9854
Epoch 90/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.3940 - mae: 1.8447
Epoch 91/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.9275 - mae: 1.8984
Epoch 92/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.4183 - mae: 1.8075
Epoch 93/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.7875 - mae: 1.8739
Epoch 94/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2390 - mae: 1.8787
Epoch 95/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 8.9735 - mae: 1.9986
Epoch 96/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.5141 - mae: 1.8592
Epoch 97/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.4259 - mae: 2.0254
Epoch 98/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 6.8892 - mae: 1.8085
Epoch 99/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 7.6303 - mae: 1.9084
Epoch 100/100
26/26 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 5.3901 - mae: 1.7055

In [44]:
y_pred = model.predict(x_test)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

In [49]:
from sklearn.metrics import mean_squared_error,r2_score

mse = mean_squared_error(y_test, y_pred)
r2square = r2_score(y_test,y_pred)

print("MSE:", mse)
print("R2 Square: ",r2square)

MSE: 10.17659604183867
R2 Square:  0.9102806241328694